name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  debug-setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      
    - name: Set up Python 3.12
      run: uv python install 3.12
      
    - name: Debug - Show Python and UV info
      run: |
        echo "=== UV Info ==="
        uv --version
        echo "=== Python Info ==="
        uv run python --version
        uv run python -c "import sys; print(f'Python executable: {sys.executable}')"
        uv run python -c "import sys; print(f'Python path: {sys.path}')"
        echo "=== Working Directory ==="
        pwd
        ls -la
        echo "=== Project Structure ==="
        find . -name "*.py" | head -20
        
    - name: Install dependencies
      run: |
        echo "=== Installing dependencies ==="
        uv sync --dev --verbose
        echo "=== Installed packages ==="
        uv pip list
        
    - name: Test imports without tests
      run: |
        echo "=== Testing basic imports ==="
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        uv run python -c "
        import sys
        print('Python path:', sys.path)
        print('Current working directory:', __import__('os').getcwd())
        "
        
        echo "=== Testing specific imports ==="
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        uv run python -c "
        try:
            from entity.entity import Hand
            print('✓ entity.entity import successful')
        except Exception as e:
            print('✗ entity.entity import failed:', e)
        "
        
        uv run python -c "
        try:
            from exceptions.exceptions import AgentSetupError
            print('✓ exceptions import successful')
        except Exception as e:
            print('✗ exceptions import failed:', e)
        "

  basic-test:
    runs-on: ubuntu-latest
    needs: debug-setup
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      
    - name: Set up Python 3.12
      run: uv python install 3.12
      
    - name: Install dependencies
      run: uv sync --dev
      
    - name: Test basic functionality
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        echo "=== Testing generator import ==="
        uv run python -c "
        try:
            from generator.generator import MahjongQuestionGenerator
            print('✓ Generator import successful')
        except Exception as e:
            print('✗ Generator import failed:', e)
            import traceback
            traceback.print_exc()
        "
        
        echo "=== Testing evaluator import ==="
        uv run python -c "
        try:
            from evaluator.evaluator import MahjongEvaluator
            print('✓ Evaluator import successful')
        except Exception as e:
            print('✗ Evaluator import failed:', e)
            import traceback
            traceback.print_exc()
        "

  syntax-check:
    runs-on: ubuntu-latest
    needs: debug-setup
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      
    - name: Set up Python 3.12
      run: uv python install 3.12
      
    - name: Install dependencies
      run: uv sync --dev
      
    - name: Check syntax of all Python files
      run: |
        echo "=== Checking syntax ==="
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        
        # Check main modules
        uv run python -m py_compile generator/generator.py
        uv run python -m py_compile evaluator/evaluator.py
        uv run python -m py_compile evaluator/libs.py
        uv run python -m py_compile entity/entity.py
        uv run python -m py_compile exceptions/exceptions.py
        
        # Check test files
        uv run python -m py_compile tests/test_generator.py
        uv run python -m py_compile tests/test_evaluator.py
        uv run python -m py_compile tests/test_evaluator_libs.py
        uv run python -m py_compile tests/run_tests.py
        
        echo "✓ All syntax checks passed"

  simple-test:
    runs-on: ubuntu-latest
    needs: [debug-setup, basic-test, syntax-check]
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      
    - name: Set up Python 3.12
      run: uv python install 3.12
      
    - name: Install dependencies
      run: uv sync --dev
      
    - name: Run simple test
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        echo "=== Running one simple test ==="
        uv run python -m pytest tests/test_generator.py::TestMahjongQuestionGenerator::test_init_simple_mode -v -s