name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --dev

    - name: Show environment info
      run: |
        uv --version
        uv run python --version
        uv pip list

    - name: Debug environment
      run: |
        echo "Working directory: $(pwd)"
        echo "Python path:"
        uv run python -c "import sys; [print(f'  {p}') for p in sys.path]"
        echo "Project structure:"
        find . -name "*.py" -type f | head -20
        echo "Can import basic modules?"
        uv run python -c "import sys, os; print('Basic imports work')"

    - name: Test imports
      run: |
        echo "Testing imports..."
        uv run python -c "
        try:
            import entity.entity
            print('✓ entity.entity import works')
        except Exception as e:
            print(f'✗ entity.entity import failed: {e}')
            import traceback
            traceback.print_exc()
        "
        
        uv run python -c "
        try:
            import exceptions.exceptions
            print('✓ exceptions.exceptions import works')
        except Exception as e:
            print(f'✗ exceptions.exceptions import failed: {e}')
            import traceback
            traceback.print_exc()
        "

    - name: Run linting
      run: |
        uv run ruff check .
        uv run ruff format --check .

    - name: Run tests
      run: uv run pytest -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  test-generator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --dev

    - name: Run generator tests
      run: uv run python tests/run_tests.py generator

  test-evaluator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --dev

    - name: Run evaluator tests
      run: uv run python tests/run_tests.py evaluator

  integration-test:
    runs-on: ubuntu-latest
    needs: [test, test-generator, test-evaluator]
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --dev

    - name: Run all tests together
      run: uv run python tests/run_tests.py

    - name: Test imports
      run: |
        uv run python -c "from generator.generator import MahjongQuestionGenerator; print('Generator import successful')"
        uv run python -c "from evaluator.evaluator import MahjongEvaluator; print('Evaluator import successful')"